package com.carpip.controller;

import com.carpip.entity.NegotiationLog;
import com.carpip.entity.Order;
import com.carpip.entity.User;
import com.carpip.repository.NegotiationLogRepository;
import com.carpip.repository.OrderRepository;
import com.carpip.repository.TenantRepository;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/orders")
public class OrderController {

    private final OrderRepository orderRepository;
    private final TenantRepository tenantRepository;
    private final NegotiationLogRepository negotiationLogRepository;

    public OrderController(OrderRepository orderRepository,
                           TenantRepository tenantRepository,
                           NegotiationLogRepository negotiationLogRepository) {
        this.orderRepository = orderRepository;
        this.tenantRepository = tenantRepository;
        this.negotiationLogRepository = negotiationLogRepository;
    }

    @GetMapping
    @Cacheable(value = "orders", key = "#user.tenant.id + '-' + #user.role")
    public ResponseEntity<List<Order>> getOrders(@AuthenticationPrincipal User user) {
        String tenantId = user.getTenant().getId();
        List<Order> orders;

        if (user.getRole() == User.UserRole.RETAILER) {
            orders = orderRepository.findByRetailerId(tenantId);
        } else if (user.getRole() == User.UserRole.WHOLESALER) {
            orders = orderRepository.findByWholesalerId(tenantId);
        } else {
            orders = orderRepository.findAll();
        }

        return ResponseEntity.ok(orders);
    }

    @GetMapping("/{id}")
    public ResponseEntity<Order> getOrder(@PathVariable String id) {
        Order order = orderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Order not found"));
        return ResponseEntity.ok(order);
    }

    @PostMapping
    @CacheEvict(value = {"orders", "order-stats"}, allEntries = true)
    public ResponseEntity<Order> createOrder(@RequestBody Order order, @AuthenticationPrincipal User user) {
        order.setRetailer(user.getTenant());
        order.setStatus(Order.OrderStatus.PENDING);
        Order saved = orderRepository.save(order);
        return ResponseEntity.ok(saved);
    }

    @PatchMapping("/{id}/status")
    @CacheEvict(value = {"orders", "order-stats"}, allEntries = true)
    public ResponseEntity<Order> updateOrderStatus(@PathVariable String id,
                                                     @RequestBody StatusUpdate statusUpdate,
                                                     @AuthenticationPrincipal User user) {
        Order order = orderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Order not found"));

        order.setStatus(Order.OrderStatus.valueOf(statusUpdate.status()));
        Order saved = orderRepository.save(order);
        return ResponseEntity.ok(saved);
    }

    /**
     * Get negotiation logs for a specific order.
     */
    @GetMapping("/{id}/negotiations")
    public ResponseEntity<List<NegotiationLog>> getOrderNegotiations(@PathVariable String id) {
        List<NegotiationLog> logs = negotiationLogRepository.findByOrderIdOrderByTimestampAsc(id);
        return ResponseEntity.ok(logs);
    }

    /**
     * Get auto-procurement orders (auto-generated by ERP sync when stock is low).
     */
    @GetMapping("/auto-procurement")
    public ResponseEntity<List<Order>> getAutoProcurementOrders(@AuthenticationPrincipal User user) {
        String tenantId = user.getTenant().getId();
        List<Order> autoOrders;

        if (user.getRole() == User.UserRole.ADMIN) {
            autoOrders = orderRepository.findByAutoGenerated(true);
        } else {
            autoOrders = orderRepository.findByRetailerIdAndAutoGenerated(tenantId, true);
        }

        return ResponseEntity.ok(autoOrders);
    }

    /**
     * Get summary statistics for orders.
     */
    @GetMapping("/stats")
    @Cacheable(value = "order-stats", key = "#user.tenant.id + '-' + #user.role")
    public ResponseEntity<Map<String, Object>> getOrderStats(@AuthenticationPrincipal User user) {
        String tenantId = user.getTenant().getId();
        List<Order> orders;

        if (user.getRole() == User.UserRole.RETAILER) {
            orders = orderRepository.findByRetailerId(tenantId);
        } else if (user.getRole() == User.UserRole.WHOLESALER) {
            orders = orderRepository.findByWholesalerId(tenantId);
        } else {
            orders = orderRepository.findAll();
        }

        long pending = orders.stream().filter(o -> o.getStatus() == Order.OrderStatus.PENDING).count();
        long negotiating = orders.stream().filter(o -> o.getStatus() == Order.OrderStatus.NEGOTIATING).count();
        long accepted = orders.stream().filter(o -> o.getStatus() == Order.OrderStatus.ACCEPTED).count();
        long rejected = orders.stream().filter(o -> o.getStatus() == Order.OrderStatus.REJECTED).count();
        long fulfilled = orders.stream().filter(o -> o.getStatus() == Order.OrderStatus.FULFILLED).count();
        long shipped = orders.stream().filter(o -> o.getStatus() == Order.OrderStatus.SHIPPED).count();
        long autoGenerated = orders.stream().filter(o -> Boolean.TRUE.equals(o.getAutoGenerated())).count();

        // Calculate total AI savings
        double totalSavings = orders.stream()
                .filter(o -> o.getNegotiatedSavings() != null)
                .mapToDouble(o -> o.getNegotiatedSavings().doubleValue())
                .sum();

        Map<String, Object> stats = new java.util.HashMap<>();
        stats.put("total", orders.size());
        stats.put("pending", pending);
        stats.put("negotiating", negotiating);
        stats.put("accepted", accepted);
        stats.put("rejected", rejected);
        stats.put("fulfilled", fulfilled);
        stats.put("shipped", shipped);
        stats.put("autoGenerated", autoGenerated);
        stats.put("totalSavings", totalSavings);

        return ResponseEntity.ok(stats);
    }

    public record StatusUpdate(String status) {}
}
