package com.carpip.entity;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "orders")
public class Order {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "retailer_id", nullable = false)
    private Tenant retailer;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "wholesaler_id")
    private Tenant wholesaler;

    @Column(name = "po_number", unique = true)
    private String poNumber;

    @Column(name = "source_sku")
    private String sourceSku;

    @Column(name = "auto_generated")
    private Boolean autoGenerated;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private OrderStatus status;

    @Column(name = "total_amount", precision = 12, scale = 2)
    private BigDecimal totalAmount;

    @Column(name = "negotiated_savings", precision = 10, scale = 2)
    private BigDecimal negotiatedSavings;

    @Column(name = "items_json", columnDefinition = "text")
    private String itemsJson;

    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    public enum OrderStatus {
        PENDING, NEGOTIATING, ACCEPTED, REJECTED, FULFILLED, SHIPPED
    }

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
        if (status == null) status = OrderStatus.PENDING;
        if (poNumber == null || poNumber.isEmpty()) {
            poNumber = "PO-" + java.time.Year.now().getValue() + "-" +
                    String.format("%04d", (int) (Math.random() * 9000) + 1000);
        }
        if (autoGenerated == null) autoGenerated = false;
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    // Getters and Setters
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public Tenant getRetailer() { return retailer; }
    public void setRetailer(Tenant retailer) { this.retailer = retailer; }

    public Tenant getWholesaler() { return wholesaler; }
    public void setWholesaler(Tenant wholesaler) { this.wholesaler = wholesaler; }

    public String getPoNumber() { return poNumber; }
    public void setPoNumber(String poNumber) { this.poNumber = poNumber; }

    public String getSourceSku() { return sourceSku; }
    public void setSourceSku(String sourceSku) { this.sourceSku = sourceSku; }

    public Boolean getAutoGenerated() { return autoGenerated; }
    public void setAutoGenerated(Boolean autoGenerated) { this.autoGenerated = autoGenerated; }

    public OrderStatus getStatus() { return status; }
    public void setStatus(OrderStatus status) { this.status = status; }

    public BigDecimal getTotalAmount() { return totalAmount; }
    public void setTotalAmount(BigDecimal totalAmount) { this.totalAmount = totalAmount; }

    public BigDecimal getNegotiatedSavings() { return negotiatedSavings; }
    public void setNegotiatedSavings(BigDecimal negotiatedSavings) { this.negotiatedSavings = negotiatedSavings; }

    public String getItemsJson() { return itemsJson; }
    public void setItemsJson(String itemsJson) { this.itemsJson = itemsJson; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public LocalDateTime getUpdatedAt() { return updatedAt; }
}
